package com.chengxh.springbootdemo.entity;

public class ScoreKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.s_id
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    private String sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.c_id
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    private String cId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.s_id
     *
     * @return the value of score.s_id
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    public String getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.s_id
     *
     * @param sId the value for score.s_id
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    public void setsId(String sId) {
        this.sId = sId == null ? null : sId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.c_id
     *
     * @return the value of score.c_id
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.c_id
     *
     * @param cId the value for score.c_id
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }
}