package com.chengxh.springbootdemo.entity;

public class Score extends ScoreKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.s_score
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    private Integer sScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.s_score
     *
     * @return the value of score.s_score
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    public Integer getsScore() {
        return sScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.s_score
     *
     * @param sScore the value for score.s_score
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    public void setsScore(Integer sScore) {
        this.sScore = sScore;
    }
}