package com.chengxh.springbootdemo.entity;

import java.io.Serializable;

public class Student implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 4132821744162560260L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_id
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    private String sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_name
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    private String sName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_birth
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    private String sBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_sex
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    private String sSex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_id
     *
     * @return the value of student.s_id
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    public String getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_id
     *
     * @param sId the value for student.s_id
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    public void setsId(String sId) {
        this.sId = sId == null ? null : sId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_name
     *
     * @return the value of student.s_name
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_name
     *
     * @param sName the value for student.s_name
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_birth
     *
     * @return the value of student.s_birth
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    public String getsBirth() {
        return sBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_birth
     *
     * @param sBirth the value for student.s_birth
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    public void setsBirth(String sBirth) {
        this.sBirth = sBirth == null ? null : sBirth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_sex
     *
     * @return the value of student.s_sex
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    public String getsSex() {
        return sSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_sex
     *
     * @param sSex the value for student.s_sex
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    public void setsSex(String sSex) {
        this.sSex = sSex == null ? null : sSex.trim();
    }
}