package com.chengxh.springbootdemo.entity;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_id
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    private String tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_name
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    private String tName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_id
     *
     * @return the value of teacher.t_id
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    public String gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_id
     *
     * @param tId the value for teacher.t_id
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    public void settId(String tId) {
        this.tId = tId == null ? null : tId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_name
     *
     * @return the value of teacher.t_name
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_name
     *
     * @param tName the value for teacher.t_name
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    public void settName(String tName) {
        this.tName = tName == null ? null : tName.trim();
    }
}