package com.chengxh.springbootdemo.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.chengxh.springbootdemo.entity.Score;
import com.chengxh.springbootdemo.entity.ScoreExample;
import com.chengxh.springbootdemo.entity.ScoreKey;

public interface ScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    long countByExample(ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    int deleteByExample(ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    int deleteByPrimaryKey(ScoreKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    int insert(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    int insertSelective(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    List<Score> selectByExample(ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    Score selectByPrimaryKey(ScoreKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    int updateByExampleSelective(@Param("record") Score record, @Param("example") ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    int updateByExample(@Param("record") Score record, @Param("example") ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    int updateByPrimaryKeySelective(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Fri Mar 22 13:33:11 CST 2019
     */
    int updateByPrimaryKey(Score record);
}